package com.stkmrkt.stockdetails.entity;

import java.util.Date;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

import com.fasterxml.jackson.annotation.JsonIgnore;

//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerated;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Document(collection = "stock_details")
//@DynamoDBTable(tableName = "stock_details")
public class StockDetailEntity {

	@Id
	@Field("_id")
	@JsonIgnore
//	@DynamoDBHashKey
//	@DynamoDBAutoGeneratedKey
	private String id;
	
//	@DynamoDBAttribute
	private Long companyCode;
	
//	@DynamoDBAttribute
	private Double stockPrice;
	
//	@DynamoDBAttribute
	private Date stockUpdtTms;

}